name: Bug
description: Report issues extension
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: '# Bug'
  - type: textarea
    id: description
    attributes:
      label: What issue did you encounter?
      description: |
        Please provide a clear description of the bug.

    validations:
      required: true
  - type: textarea
    id: behavior
    attributes:
      label: What is the expected behaviour?
      description: What did you expect to happen instead of the current behavior?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Additional information
      description:  |
        Details like the kubectl version, vscode version, operating system in which the bug was encountered.
    validations:
      required: false
  - type: checkboxes
    id: interested-in-raising-pr
    attributes:
      label: Code contribution
      options:
        - label: Are you interested in raising a PR for this fix?
          required: false