name: Build VSIX

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.18.3
      uses: actions/setup-node@v4
      with:
        node-version: 20.18.3
        cache: 'npm'
    - name: Build View
      run: |
        cd kube-helper-view
        npm install
        npm run build
    - name: install vsce
      run: npm install -g vsce
    - name: Build VSIX
      run: |
        npm install
        vsce package
    - uses: actions/upload-artifact@v4
      with:
        name: ext-release
        path: '*.vsix'

